Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -11,25 +11,32 @@ env:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
-
     steps:
     - uses: actions/checkout@v3
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
-        dotnet-version: ${{ env.DOTNET_VERSION }}
+        dotnet-version: ${{ env.dotnet_version }}
     - name: Restore dependencies
       run: dotnet restore
     - name: Build
       run: dotnet build --no-restore
     - name: Test
-      run: dotnet test --logger trx --results-directory "TestResults-${{ env.DOTNET_VERSION }}"
+      run: dotnet test --logger "trx;logfilename=testResults.trx"
     - name: Upload dotnet test results
       uses: actions/upload-artifact@v3
       with:
-        name: dotnet-results-${{ env.DOTNET_VERSION }}
-        path: TestResults-${{ env.DOTNET_VERSION }}
+        name: dotnet-results-${{ env.dotnet_version }}
+        path: TestResults-${{ env.dotnet_version }}
       # Use always() to always run this step to publish test results when there are test failures
-      if: ${{ always() }}  
+      if: success() || failure()
+      
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: xUnit Tests           
+        path: TestResults-${{ env.dotnet_version }}
+        reporter: dotnet-trx        
+      
